[env:heltec_vision_master_e213]
platform  = espressif32
board     = heltec_vision_master_e213
framework = arduino

build_flags    = -D Vision_Master_E213

monitor_speed  = 115200
upload_speed   = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    ricmoo/QRCode @ ^0.0.1
    todd-herbert/heltec-eink-modules @ ^4.5.0
